services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonar-network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db-sonar

  db-sonar:
    image: postgres:15
    container_name: db-sonar
    networks:
      - sonar-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

networks:
  sonar-network:

volumes:
  sonar_db_data: