sonar.projectKey=devflima_flima.dev_frontend
sonar.organization=devflima
sonar.sources=src
sonar.tests=src/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/test/**, node_modules/**, dist/**
