services:
  postgres:
    image: postgres:15-alpine
    container_name: flima-postgres-local
    environment:
      POSTGRES_USER: flima
      POSTGRES_PASSWORD: flima_password
      POSTGRES_DB: flima_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flima -d flima_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    container_name: flima-kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-console:
    image: redpandadata/console:latest
    container_name: flima-kafka-console-local
    environment:
      KAFKA_BROKERS: kafka:29092
    ports:
      - "8085:8080"
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: flima-prometheus-local
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"

  health-exporter:
    image: node:18-alpine
    container_name: flima-health-exporter
    volumes:
      - ./monitoring/prometheus/health-exporter.js:/app/health-exporter.js:ro
    working_dir: /app
    command: node health-exporter.js
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9999:9999"

  grafana:
    image: grafana/grafana:10.4.0
    container_name: flima-grafana-local
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${MAIL_HOST:-smtp.gmail.com}:${MAIL_PORT:-465}
      - GF_SMTP_USER=${MAIL_USERNAME:-}
      - GF_SMTP_PASSWORD=${MAIL_PASSWORD:-}
      - GF_SMTP_FROM_ADDRESS=${MAIL_FROM:-contato@flima.dev}
      - GF_SMTP_FROM_NAME=Grafana Alerts
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
