package dev.flima.application.educations.usecases;

import dev.flima.application.educations.dtos.request.EducationDTORequest;
import dev.flima.application.educations.dtos.response.EducationDTOResponse;
import dev.flima.domain.educations.Education;
import dev.flima.domain.educations.EducationRepository;
import dev.flima.domain.educations.TypeEducation;
import dev.flima.domain.exceptions.EntityNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UpdateEducationUseCaseTest {

    @Mock
    private EducationRepository educationRepository;

    private UpdateEducationUseCase updateEducationUseCase;

    @BeforeEach
    void setUp() {
        updateEducationUseCase = new UpdateEducationUseCase(educationRepository);
    }

    @Test
    @DisplayName("Should update education successfully")
    void shouldUpdateSuccessfully() {
        // Arrange
        UUID id = UUID.randomUUID();
        Education existingEducation = new Education(
                TypeEducation.DEGREE,
                "Old Degree",
                "Old Title",
                "Old Inst",
                "2020",
                "Old Spec",
                List.of(),
                List.of()
        );
        // Set ID manually since it's usually generated by DB or set during creation
        // But for mock existing we need to make sure it looks real
        
        when(educationRepository.getById(id)).thenReturn(Optional.of(existingEducation));

        EducationDTORequest updateRequest = new EducationDTORequest(
                TypeEducation.DEGREE,
                "New Degree",
                "New Title",
                "New Inst",
                "2021",
                "New Spec",
                List.of("Skill"),
                List.of("Arch")
        );

        // Act
        EducationDTOResponse response = updateEducationUseCase.execute(id, updateRequest);

        // Assert
        assertNotNull(response);
        assertEquals("New Title", response.title());
        assertEquals("New Degree", response.degree());
        
        verify(educationRepository, times(1)).modify(any(Education.class));
    }

    @Test
    @DisplayName("Should throw EntityNotFoundException when education does not exist")
    void shouldThrowExceptionWhenNotFound() {
        // Arrange
        UUID id = UUID.randomUUID();
        when(educationRepository.getById(id)).thenReturn(Optional.empty());

        EducationDTORequest request = new EducationDTORequest(
                TypeEducation.DEGREE, "D", "T", "I", "P", "S", List.of(), List.of()
        );

        // Act & Assert
        assertThrows(EntityNotFoundException.class, () -> updateEducationUseCase.execute(id, request));
    }
}
