ALTER TABLE stats ALTER COLUMN yearsExperience TYPE VARCHAR(50);
ALTER TABLE stats ALTER COLUMN systemDeployed TYPE VARCHAR(50);
ALTER TABLE stats ALTER COLUMN uptimeSLA TYPE VARCHAR(50);
ALTER TABLE stats ALTER COLUMN commitsLogged TYPE VARCHAR(50);
ALTER TABLE stats ALTER COLUMN status TYPE VARCHAR(100);
ALTER TABLE stats ALTER COLUMN objective TYPE VARCHAR(255);

ALTER TABLE users ALTER COLUMN username TYPE VARCHAR(50);
ALTER TABLE users ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE users ALTER COLUMN last_name TYPE VARCHAR(100);
