# Configurações para ambiente de Desenvolvimento Local (Perfil 'dev')
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/meu_db

%dev.quarkus.mailer.host=smtp.zoho.com
%dev.quarkus.mailer.port=465
%dev.quarkus.mailer.mock=true
