# Configurações para ambiente de Desenvolvimento Local (Perfil 'dev')
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/flima_db
%dev.quarkus.datasource.username=flima
%dev.quarkus.datasource.password=flima_password

# Configuraçoes para ambiente de Desenvolvimento do Mailer
%dev.quarkus.mailer.host=smtp.zoho.com
%dev.quarkus.mailer.port=465
%dev.quarkus.mailer.mock=true