# -------------> CONFIGURAÇÕES Hibernate <-------------
quarkus.hibernate-orm.database-generation=none
quarkus.hibernate-orm.statistics=true

# -------------> CONFIGURAÇÕES Database <-------------
quarkus.datasource.db-kind=postgresql

# -------------> CONFIGURAÇÕES Flyway <-------------
quarkus.flyway.migrate-at-start=true

# -------------> CONFIGURAÇÕES Mailer <-------------
quarkus.mailer.mock=false

# -------------> CONFIGURAÇÕES JWT <-------------
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:classpath:privateKey.pk8}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:classpath:publicKey.pem}
mp.jwt.verify.issuer=https://flima.dev

# -------------> CONFIGURAÇÕES Kafka <-------------
mp.messaging.outgoing.contact-out.connector=smallrye-kafka
mp.messaging.outgoing.contact-out.topic=contact-messages
mp.messaging.outgoing.contact-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.contact-in.connector=smallrye-kafka
mp.messaging.incoming.contact-in.topic=contact-messages
mp.messaging.incoming.contact-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.contact-in.group.id=contact-group
mp.messaging.incoming.contact-in.retry=true
mp.messaging.incoming.contact-in.retry-attempts=3
mp.messaging.incoming.contact-in.retry-delay=2000
mp.messaging.incoming.contact-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.contact-in.dead-letter-queue.topic=contact-messages-dlq

# -------------> CONFIGURAÇÕES HTTP / CORS <-------------
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173/, https://flima.dev/
quarkus.http.cors.methods=GET,PUT,POST,DELETE
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.access-control-max-age=24h

# -------------> CONFIGURAÇÕES Bucket4j <-------------
quarkus.bucket4j.methods."dev.flima.presentation.rest.auth.AuthResource.login".limits[0].permitted-uses=5
quarkus.bucket4j.methods."dev.flima.presentation.rest.auth.AuthResource.login".limits[0].period=1m

# -------------> CONFIGURAÇÕES Prometheus <-------------
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.kafka.enabled=true