# -------------> CONFIGURAÇÕES Database (PROD) <-------------
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}

# -------------> CONFIGURAÇÕES Mailer (PROD) <-------------
quarkus.mailer.host=${MAIL_HOST}
quarkus.mailer.port=${MAIL_PORT}
quarkus.mailer.tls=true
quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.password=${MAIL_PASSWORD}
quarkus.mailer.from=${MAIL_FROM}
