# Permite que o Hibernate envie Strings para ENUMs no PostgreSQL (usado com o V999__Test_Casts.sql)
quarkus.datasource.jdbc.additional-jdbc-url-parameters=stringtype=unspecified

# Inclui as migrações de teste que adicionam os CASTs necessários
quarkus.flyway.locations=db/migration,classpath:db/test-migration
